[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
auto_detect_remappings = true
dynamic_test_linking = true
gas_reports = ["*"]
verbosity = 4
ffi = false
fs_permissions = [{ access = "read", path = "./" }]
extra_output = ["storageLayout", "metadata"]
bytecode_hash = "ipfs"
cbor = false
evm_version = "paris"
revert_strings = "default"

[profile.default.fuzz]
runs = 1000
max_local_rejects = 10000
max_global_rejects = 10000

[profile.default.invariant]
runs = 256
depth = 15
fail_on_revert = false

[profile.default.metadata]
bytecode_hash = "ipfs"

[profile.default.metadata.settings]
optimizer = { enabled = true, runs = 200 }
via_ir = false
evm_version = "paris"

# RPC endpoints for deployment and testing
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
anvil = "http://localhost:8545"

# Etherscan API keys for contract verification
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }

# Linting configuration
[lint]
exclude_lints = ["divide-before-multiply"]
